import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import {Header} from "@/components/header";
import {Footer} from "@/components/footer";
import {PropsWithChildren} from "react";

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Amerikan aptek',
  description: 'Generated by create next app',
}

interface RootLayoutProps extends PropsWithChildren{

}

export default function RootLayout(props: RootLayoutProps) {
  const {children} = props;
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className={'flex flex-col h-full'}>
          <Header />
          <main className={'flex-1'}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
